################ English language ##################
[en]
languageName = "en"
languageCode = "ja-jp"
contentDir = "content/english"
weight = 1

# post pagination
paginate = 20 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 30 # see https://gohugo.io/content-management/excerpts/
# disable language
disableLanguages = [
] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = true #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage
# default language
